Work.WebProj/Controllers/IndexController.cs
using System.Linq;
using System.Web.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Text;
using System.IO;
using System;
using System.Collections.Generic;
using System.Net.Mail;
using ProcCore.HandleResult;
using DotWeb.CommSetup;
using DotWeb.Controller;
using ProcCore.Business.DB0;
using System.Web;

namespace DotWeb.Controllers
{
    public class IndexController : WebUserController
    {
        public ActionResult Index()
        {
            IList<News> news = new List<News>();
            using (var db0 = getDB0())
            {
                news = db0.News.Where(x => x.i_Hide == false & x.i_Lang == System.Globalization.CultureInfo.CurrentCulture.Name).OrderByDescending(x => x.news_date).Take(10).ToList();

                foreach (var item in news)
                {
                    item.imgsrc = GetImg(item.news_id, "Photo1", "News", "News");//顯示列表圖
                }
            }
            return View(news);
        }

        public RedirectResult Login()
        {
            return Redirect("~/Base/Login");
        }
    }
}

Work.WebProj/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="各材種封邊木皮,熱熔膠機械設備,PUR熱熔膠,各類膠膜膠網,車燈業用膠,複合材料用膠,紡織業用膠,中空玻璃相關產品,工業用膠,熱熔膠,包裝用膠">
    <meta name="description" content="富利源企業有限公司於１９９２年３月設立於桃園，二十餘年來一直秉持著專業理念致力於接著劑【膠】及綠能遮光材料開發與製造加工並以ＯＬＥＣ品牌銷售世界30餘國。 同時代理國際大廠高分子相關產品.">
    <title>OLEC 富利源企業有限公司-水性接著劑、工業用膠、熱熔膠、包裝用膠:@ViewBag.Title</title>

    <!--[if lt IE 9]><script src="//ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script><![endif]-->
    <script src="~/Scripts/app/BrowerInfo.js"></script>
    <script>
        var gb_approot = '@Url.Content("~")';
    </script>
    <link rel="alternate" href="http://www.olecgroup.com/?lang=zh-TW" hreflang="zh-Hant">
    <link rel="alternate" href="http://www.olecgroup.com/?lang=en-US" hreflang="en">
    <link rel="stylesheet" href="~/Content/css/swiper.css">
    @if (ViewBag.IsFirstPage) {
    <link rel="stylesheet" href="~/Content/css/index.css">
    } else {
    <link rel="stylesheet" href="~/Content/css/page.css">
    }
    @RenderSection("css", false)
</head>

<body class="@ViewBag.BodyClass">

<div id="wrapper">

    <section id="header">
        <div class="wrap">
            <h1 onclick="location.href='@Url.Content("~/index")'" title="回首頁">OLEC富利源企業有限公司</h1>
            <nav id="menu">
                <a href="~/index">HOME</a>
                <a href="~/AboutUs">公司簡介</a>
                <a href="~/Products">產品介紹</a>
                <a href="~/News">最新消息</a>
                <a href="~/ContactUs">聯絡我們</a>
            </nav>
            <nav class="top-nav">
                <a href="@Url.Action("index")?lang=zh-TW">::繁體中文</a>
                <a href="@Url.Action("index")?lang=en-US">::English</a>
            </nav>
        </div><!-- wrap //-->
        <div id="banner" class="swiper-container">
            <div class="swiper-wrapper">
            @if (ViewBag.IsFirstPage)
            {
                <li class="swiper-slide i1">banner 1</li>
                <li class="swiper-slide i2">banner 2</li>
                <li class="swiper-slide i3">banner 3</li>
            }
            else
            {
                <li class="swiper-slide i1">banner 1</li>
                <li class="swiper-slide i2">banner 2</li>
            }
            </div>
        </div><!-- banner //-->
    </section><!-- header //-->

    <main>
        @RenderBody()
    </main>

</div><!-- wrapper //-->

<section id="footer">
    <ul class="list-inline">
        <li>桃園市龍潭區高楊北路452巷28號</li>
        <li><em>TEL:</em>+886 3-411-7500<br><em>FAX:</em>+886 3-411-7963</li>
        <li><em>Mail:</em><a href="mailto:super@olecgroup.com">super@olecgroup.com</a></li>
    </ul>
    <div class="copyright"><span>OLEC</span>&copy; 2015 富利源企業有限公司 86597773</div>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1810.3706362840921!2d121.20784130000001!3d24.838520100000004!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x34683c48d5c20e31%3A0x72e8b31495e66ceb!2zMzI15qGD5ZyS5biC6b6N5r2t5Y2A6auY5qWK5YyX6LevMjjomZ8!5e0!3m2!1szh-TW!2stw!4v1440400062208" width="620" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>
</section><!-- footer -->

<script src="//code.jquery.com/jquery-latest.min.js"></script>
<script src="~/Content/js/swiper.jquery.min.js"></script>
<script src="~/Content/js/scroll.js"></script>
<script src="~/Content/js/jquery.marquee.min.js"></script>

<script>
// 跑馬燈
$("#marquee").marquee();

// swiper 輪播圖
var mySwiper = new Swiper('#banner',{
    loop: true,
    autoplay: 4000,
    speed: 1000,
    effect: 'fade',
    autoplayDisableOnInteraction: false
})
</script>

@RenderSection("Scripts", required: false)

</body>
</html>

Work.WebProj/Views/Shared/Layout.en-US.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="B.D. of Macromolecule and Materials is in charge of selling macromolecule-related products from world renowned corporations, including polyester polyol, EVA emulsion, acrylic acid emulsion, etc.">
    <meta name="description" content="Ocean Land Enterprise Co., Ltd. was established in Taoyuan, in March, 1992. OLEC has been devoted in developing and manufacturing adhesive and eco light-blocking materials for more than 20 years.">
    <title>OLEC Ocean Land Enterprise Co., Ltd.We produce water-based adhesive, polyurethane peactive (PUR), eco hot-melt adhesive:@ViewBag.Title</title>

    <!--[if lt IE 9]><script src="//ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script><![endif]-->
    <script src="~/Scripts/app/BrowerInfo.js"></script>
    <script>
        var gb_approot = '@Url.Content("~")';
    </script>
    <link rel="alternate" href="http://www.olecgroup.com/?lang=en-US" hreflang="en">
    <link rel="alternate" href="http://www.olecgroup.com/?lang=zh-TW" hreflang="zh-Hant">
    <link rel="stylesheet" href="~/Content/css/swiper.css">
    @if (ViewBag.IsFirstPage) {
    <link rel="stylesheet" href="~/Content/css/index.css">
    } else {
    <link rel="stylesheet" href="~/Content/css/page.css">
    }
    <link rel="stylesheet" href="~/Content/css/en.css">
    @RenderSection("css", false)
</head>

<body class="@ViewBag.BodyClass">

<div id="wrapper">

    <section id="header">
        <div class="wrap">
            <h1 onclick="location.href='@Url.Content("~/index")'" title="HOME">Ocean Land Enterprise Co., Ltd | OLEC Technology Co., Ltd</h1>
            <nav id="menu">
                <a href="~/index">HOME</a>
                <a href="~/AboutUs">ABOUT US</a>
                <a href="~/Products">PRODUCTS</a>
                <a href="~/News">NEWS</a>
                <a href="~/ContactUs">CONTACT US</a>
            </nav>
            <nav class="top-nav">
                @*<a href="@Url.Action("SetLanguage")?L=zh-TW&A=index">::繁體中文</a>
                <a href="@Url.Action("SetLanguage")?L=en-US&A=index">::English</a>*@
                <a href="@Url.Action("index")?lang=zh-TW">::繁體中文</a>
                <a href="@Url.Action("index")?lang=en-US">::English</a>
            </nav>
        </div><!-- wrap //-->
        <div id="banner" class="swiper-container">
            <div class="swiper-wrapper">
            @if (ViewBag.IsFirstPage)
            {
                <li class="swiper-slide i1">banner 1</li>
                <li class="swiper-slide i2">banner 2</li>
                <li class="swiper-slide i3">banner 3</li>
            }
            else
            {
                <li class="swiper-slide i1">banner 1</li>
                <li class="swiper-slide i2">banner 2</li>
            }
            </div>
        </div><!-- banner //-->
    </section><!-- header //-->

    <main>
        @RenderBody()
    </main>

</div><!-- wrapper //-->

<section id="footer">
    <ul class="list-inline">
        <li>No.28, Ln. 452, Gaoyang N. Rd., Longtan Dist., Taoyuan City 325, Taiwan (R.O.C.)</li>
        <li><em>TEL:</em>+886 3-411-7500<br><em>FAX:</em>+886 3-411-7963</li>
        <li><em>Mail:</em><a href="mailto:super@olecgroup.com">super@olecgroup.com</a></li>
    </ul>
    <div class="copyright"><span>OLEC</span>&copy; 2015 OLEC Technology Co., Ltd 86597773</div>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1810.3706362840921!2d121.20784130000001!3d24.838520100000004!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x34683c48d5c20e31%3A0x72e8b31495e66ceb!2zMzI15qGD5ZyS5biC6b6N5r2t5Y2A6auY5qWK5YyX6LevMjjomZ8!5e0!3m2!1szh-TW!2stw!4v1440400062208" width="620" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>
</section><!-- footer -->

<script src="//code.jquery.com/jquery-latest.min.js"></script>
<script src="~/Content/js/swiper.jquery.min.js"></script>
<script src="~/Content/js/scroll.js"></script>
<script src="~/Content/js/jquery.marquee.min.js"></script>

<script>
// 跑馬燈
$("#marquee").marquee();

// swiper 輪播圖
var mySwiper = new Swiper('#banner',{
    loop: true,
    autoplay: 4000,
    speed: 1000,
    effect: 'fade',
    autoplayDisableOnInteraction: false
})
</script>

@RenderSection("Scripts", required: false)

</body>
</html>

Work.WebProj/Views/Shared/View.cshtml
<div classname="table-footer">
    <div classname="pull-left">
        <button classname="btn-link text-success"
                type="button"
                onclick={this.props.InsertType}>
            <i classname="fa-plus-circle"></i> 新增
        </button>
        <button classname="btn-link text-danger" type="button"
                onclick={this.props.deleteSubmit}>
            <i classname="fa-trash-o"></i> 刪除
        </button>
    </div>
    <small classname="pull-right">第{this.props.StartCount}-{this.props.EndCount}筆，共{this.props.RecordCount}筆</small>

    <ul classname="pager">
        <li>
            <a href="#" title="移至第一頁" tabindex="-1" onclick={this.firstPage}>
                <i classname="fa-angle-double-left"></i>
            </a>
        </li>
        <li>
            <a href="#" title="下一頁" tabindex="-1" onclick={this.prvePage}>
                <i classname="fa-angle-left"></i>
            </a>
        </li>
        <li classname="form-inline">
            <div classname="form-group">
                <label>第</label>
                {' '}
                <input classname="form-control" type="number" min="1" tabindex="-1" value={this.props.NowPage}
                       onchange={this.jumpPage} />
                {' '}
                <label>頁，共{this.props.TotalPage}頁</label>
            </div>
        </li>
        <li>
            <a href="#" title="@Resources.Res.NextPage" tabindex="-1" onclick={this.nextPage}>
                <i class="btn-warning"></i>
            </a>
        </li>
        <li>
            <a href="#" title="移至最後一頁" tabindex="-1" onclick={this.lastPage}>
                <i classname="fa-angle-double-right"></i>
            </a>
        </li>
    </ul>
</div>

Work.WebProj/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>